#!/bin/bash

# ════════════════════════════════════════════════════════════════════
# VPS MÁSTER - Gestor de Sockets SOCKS
# Creado por: SINNOMBRE22
# Fecha: 2025-10-18 03:43:41 UTC
# Compatible con: Ubuntu 22.04 LTS
# ════════════════════════════════════════════════════════════════════

install () {
    cd $HOME && mkdir socks
    cd socks
    patch="https://raw.githubusercontent.com/SINNOMBRE22/master-vps/master/Install/backsocz"
    arq="backsocz"
    wget $patch -o /dev/null
    unzip $arq > /dev/null 2>&1
    mv -f ./ssh /etc/ssh/sshd_config && service ssh restart 1> /dev/null 2>/dev/null
    mv -f sckt$(python3 --version|awk '{print $2}'|cut -d'.' -f1,2) /usr/sbin/sckt
    mv -f scktcheck /bin/scktcheck
    chmod +x /bin/scktcheck
    chmod +x  /usr/sbin/sckt
    rm -rf $HOME/socks
    cd $HOME
}

portas () {
    lsof -V -i tcp -P -n | grep -v "ESTABLISHED" |grep -v "COMMAND" | grep "LISTEN" > /tmp/pts
    while read port; do
    var1=$(echo $port | awk '{print $1}')
    var2=$(echo $port | awk '{print $9}' | awk -F ":" '{print $2}')
    if [ "$(echo $porta_var | grep "$var1" | grep "$var2")" = "" ]; then
    porta_var+="$var1 $var2\n"
    fi
    done < /tmp/pts
    echo -e "$porta_var"
    rm /tmp/pts
}

startsocks () {
[[ ! -e /etc/master-vps/cabecalho ]] && exit
install
echo -e "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -ne "\033[1;32m Mensaje: \033[1;37m"; read msg
[[ $msg = "" ]] && msg="BIENVENIDO"
echo -ne "\033[1;32m Puerto de Escucha: \033[1;37m"; read portxz
[[ $portxz = "" ]] && portxz="8080"
var=$(portas|grep $portxz)
if [[ "$var" = "" ]]; then
 screen -dmS sokz scktcheck "$portxz" "$msg" > /dev/null 2>&1
else
 echo -e "\033[1;31m ✗ ¡PUERTO EN USO!"
fi
sleep 2s
[[ "$(netstat -nltp|grep :${portxz})" != "" ]] && echo -e "\033[1;32m ✓ Conexión TCP en línea!" || echo -e "\033[1;31m ✗ ¡Conexión TCP fallida!"
echo -e "\033[0m"
echo -e "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
[[ -e /bin/scktcheck ]] && rm /bin/scktcheck
}

startsocks
